name: Trigger auto deployment for container-app-hqvmsyahbxlns

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/container-app-hqvmsyahbxlns-AutoDeployTrigger-e9560a12-92a3-4b65-ab82-0584e93ee4a8.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CONTAINERAPPHQVMSYAHBXLNS_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CONTAINERAPPHQVMSYAHBXLNS_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CONTAINERAPPHQVMSYAHBXLNS_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: containerregistryhqvmsyahbxlns.azurecr.io
          registryUsername: ${{ secrets.CONTAINERAPPHQVMSYAHBXLNS_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CONTAINERAPPHQVMSYAHBXLNS_REGISTRY_PASSWORD }}
          containerAppName: container-app-hqvmsyahbxlns
          resourceGroup: shopifyapptemplaterubyb37c
          imageToBuild: containerregistryhqvmsyahbxlns.azurecr.io/container-app-hqvmsyahbxlns:${{ github.sha }}
          dockerfilePath: Dockerfile


